version: '3.7'
services:
    cadvisor:
      container_name: cadvisor
      network_mode: network #replace with your docker network
      image: gcr.io/cadvisor/cadvisor:latest
      restart: always
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      ports:
        - 8013:8080 # Replace with your open port