version: '3.7'
services:
  prometheus:
    container_name: prometheus
    hostname: prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: network #replace with your docker network
    image: ubuntu/prometheus:latest
    restart: always
    user: '1000' # replace with your ID User Linux
    environment:
      - PUID=1000
      - PGID=1000
    deploy:
      resources: # replace with the most appropriate resources
        limits:
          memory: 1024M
        reservations:
            memory: 500M
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 8011:9090 # Replace with your open port
  node-exporter:
    container_name: node-exporter
    hostname: node-exporter
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: prom/node-exporter:latest
    network_mode: network #replace with your docker network
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 8012:9100 # Replace with your open port