global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['10.10.10.4:8011'] # replace with your IP server and open port
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.10.10.4:8012'] # replace with your IP server and open port
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.10.4:8013'] # replace with your IP server and open port
